### PR TITLE
Adding a new property to dump entry intf

### PR DESCRIPTION
**Pull request by asmithakarun**
This interface can be implemented by the dbus objects
that has a requirement to store the unique id of the
user that has initiated the activity. This id is
stored in the "GeneratorId" property.

Signed-off-by: Asmitha Karunanithi <asmitk01@in.ibm.com>
Change-Id: Ia96592bbe4a7b0057fe66f8e1f09d73837978c30

### CODE REVIEW

**Comment by sunharis** [comment]
Code looks good. @asmithakarun you need to git add the auto-generated meson files also into the commit. They are needed for the build. Then only the CI will pass.

**Review by dhruvibm — APPROVED** [review]

**Comment by dhruvibm** [comment]
I think those unique ids need to be defined somewhere.

**Comment by asmithakarun** [comment]
> I think those unique ids need to be defined somewhere.

You mean to say, since the unique ids are generic (client ip in our case), it should be defined?
Should it be like a regex/just writing a description?

**Comment by asmithakarun** [comment]
New pr at:
https://github.com/ibm-openbmc/phosphor-dbus-interfaces/pull/28

**Pull request closed without merging**
